### ISSUE TITLE
Wifi is not working

### ISSUE THREAD

**Issue by Gipsy-mk14** [SamarV-121/android_device_realme_RMX1851#1]
[logcat_02-05-2020_17-58-26.txt](https://github.com/SamarV-121/android_device_realme_RMX1851/files/4159081/logcat_02-05-2020_17-58-26.txt)

**Comment by SamarV-121** [comment]
Its fine
Are you using stock vendor?

**Comment by Gipsy-mk14** [comment]
Yes, I am using A21 vendor sir

Pada tanggal Rab, 5 Feb 2020 19.36, Sᴀᴍᴀʀ Vɪꜱᴘᴜᴛᴇ <notifications@github.com>
menulis:
