### ISSUE TITLE
Realme 3 pro pe 11 bugs

### ISSUE THREAD

**Issue by codebyvik** [SamarV-121/android_device_realme_RMX1851#5]
pixel experience version : pe 11 beta
installation procedure : clean install 

 Bugs in a11 :
1)Can't access flashlight as it says camera is accessed by another app..
2)Camera won't be accessible from any third party apps either as some app is using it in the background 
3) there won't be default apn ..you need to add one manually to connect to data 
4) default usb configuration is set to no data transfer..you might have to change it in developer options.
[test.log](https://github.com/SamarV-121/android_device_realme_RMX1851/files/5611613/test.log)

**Comment by SamarV-121** [comment]
Everything has been fixed in [PixelExperience_RMX1851-11.0-20201129-0801-BETA-OFFICIAL.zip](https://download.pixelexperience.org/RMX1851)

**Comment by codebyvik** [comment]
thank you!!!
